---
- name: Setup handson environment
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure class_id variable is set
      fail:
        msg: "The variable 'class_id' must be defined."
      when: class_id is not defined

    - name: Ensure instance_num variable is set
      fail:
        msg: "The variable 'instance_num' must be defined."
      when: instance_num is not defined

    - name: Create a keypair
      amazon.aws.ec2_key:
        name: "{{ KEYPAIR_NAME }}-{{ class_id }}"
        region: "{{ REGION }}"
        state: present
      register: keypair

    - debug: var=keypair

    - name: Output private key
      copy:
        content: "{{ keypair.key.private_key }}"
        dest: "{{ class_id }}-{{ KEYPAIR_NAME }}.pem"
        mode: "0600"
      when: keypair.key.private_key is defined

    - name: Collect subnet info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ REGION }}"
        filters:
          "tag:role": "{{ RESOURCE_TAG_ROLE }}"
      register: subnets

    - debug: var=subnets

    - name: Fetch existing instances with specific tag
      amazon.aws.ec2_instance_info:
        filters:
          "tag:class_id": "{{ class_id }}"
      register: current_instances

    - debug: var=current_instances

    - name: Count existing instances
      set_fact:
        current_count: "{{ current_instances.instances | length }}"

    - debug: var=current_count

    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ INSTANCE_NAME_PREFIX }}-{{ class_id }}"
        key_name: "{{ KEYPAIR_NAME }}-{{ class_id }}"
        instance_type: "{{ INSTANCE_TYPE }}"
        security_group: "{{ SEC_GROUP_NAME }}"
        network_interfaces:
          - assign_public_ip: true
            subnet_id: "{{ subnets.subnets[0].id }}"
        image_id: "{{ AMI_ID }}"
        count: "{{ instance_num }}"
        tags:
          role: "{{ RESOURCE_TAG_ROLE }}"
          class_id: "{{ class_id }}"
        volumes:
          - device_name: /dev/sda1
            ebs:
              delete_on_termination: true
              volume_size: "{{ VOLUME_SIZE }}"
      when: current_count | int < instance_num | int
      register: ec2_instances

    - debug: var=ec2_instances

    - set_fact:
        ec2_instances: "{{ current_instances }}"
      when: current_count | int == instance_num | int

    - debug: var=ec2_instances

    - name: Get public IP addresses
      set_fact:
        public_ips: "{{ ec2_instances.instances | json_query('[*].network_interfaces[*].association.public_ip') | flatten }}"

    - debug: var=public_ips

    - name: create inventory for class {{ class_id }}
      ansible.builtin.copy:
        dest: "{{ class_id }}_podman_inventory"
        content: |
          {%for ip in public_ips %}
          {{ ip }}
          {% endfor %}

          [all:vars]
          ansible_user={{ EC2_USER_NAME }}
          ansible_ssh_private_key_file={{ class_id }}-{{ KEYPAIR_NAME }}.pem
          class_id={{ class_id }}
