---
- hosts: all
  become: true
  tasks:
    - ansible.builtin.ping:
      register: ret_ping
      until: ret_ping is not failed
      retries: 30
      delay: 10


    - name: OS update
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: install podman
      ansible.builtin.dnf:
        name: podman
        state: latest

    - name: reboot
      ansible.builtin.reboot:
        reboot_timeout: 180

    - ansible.builtin.ping:
